# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[â¯](bold purple)"
error_symbol = "[âœ–](bold red)"
#success_symbol = "[âœ](bold blue)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

[status]
style = "bg:blue fg:black"
symbol = "ğŸ’£ "
format = '[\[$symbol$status\]]($style) '
disabled = false

[username]
style_user = "white bold"
style_root = "red bold"
format = "user: [$user]($style) "
disabled = false
show_always = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
